### PR TITLE
Update ls detection method

### PR DESCRIPTION
**Pull request by mbazli**
1. Add method to read all LS sensors value and give output in Binary-kind format
   Example:
   S0 S1  S2  S3  S4  S5  S6
   if S0 and S1 is detected, the value will be 2^0 + 2^1 = 1+2 --> 3
   using this method, user's will write less code to compare each sensor values
   and able to practice binary style reading.

2. Put LS sensors range for detection confirmation, this to absorb tolerances given from the sensors/ambient light/line track material itself.

### CODE REVIEW

**Comment by mbazli** [comment]
@syed93uthman any reviews on this PR?

**Comment by syed93uthman** [comment]
Cool function. This function can use to switching lLF tracking strategy. 90 degree turn, T junction.  I dont see any error with this code. But i didn't have hardware yet. I will send you one LF kit

**Comment by mbazli** [comment]
Yes. better way is if I can test it on actual HW and produce some test case before accept to merge. looking forward for the FREE kit haha, tell me if you need me to cover shipping fee

**Comment by syed93uthman** [comment]
I would be nice to use this function to expand into beginner-friendly. The left most would be 1 and right most will be last number. 
S1 = 1 S2=0 S3=0   output = 1
S1 = 1 S2=1 S3=0   output = 2
S1 = 0 S2=1 S3=0   output = 3
S1 = 0 S2=1 S3=1   output = 4
S1 = 0 S2=0 S3=1   output = 5

And last read is cool feature to have

**Comment by mbazli** [comment]
yes, that will be nice to have too. But I believe that feature can be added in new branch, so more functionality in reading the sensor. Either using binary format or using sensor position format

**Comment by mbazli** [comment]
> I would be nice to use this function to expand into beginner-friendly. The left most would be 1 and right most will be last number.
> S1 = 1 S2=0 S3=0 output = 1
> S1 = 1 S2=1 S3=0 output = 2
> S1 = 0 S2=1 S3=0 output = 3
> S1 = 0 S2=1 S3=1 output = 4
> S1 = 0 S2=0 S3=1 output = 5
> 
> And last read is cool feature to have

for this feature, will do on another features branch. If nothing else to comment on this branch, please merge it so we can work on other features

**Pull request merged**
