### PR TITLE
Create branching strategy readme

### PR DESCRIPTION
**Pull request by mbazli**
1. Briefly describe branching strategy following standard from Microsoft versioning and Gitflow style

### CODE REVIEW

**Comment by hazimgharib21** [comment]
Hello,

Nice one. Maybe can do more elaboration in the future and add this file into CONTRIBUTING.md.

Some suggestions :-

1) change naming convention for feature branch. Change to feature/name-of-feature. This is needed if we want to differentiate between bug-fix and feature.
2) add hotfix/bugfix branch. This branch may branch off from develop and must be merge back into develop. Naming convention can be bugfix/name-of-bugfix. Other suggestion would be to create a release branch. So, all bugfix/hotfix will branch off release branch. bugfix/hotfix must be merge back into both release and develop branch. Some minor version bumping needed when merging.
3) Does merge in gui retain all the commit inside a branch? if not, I think it is better to for reviewer(@syed93uthman ) to merge in command line with --no-ff flag.

thanks.

**Comment by mbazli** [comment]
no. 1 & 2 agreed. will add about it in the document

no. 3, I believe the button does the same action https://help.github.com/en/articles/about-merge-methods-on-github

**Comment by mbazli** [comment]
@syed93uthman @hazimgharib21 I have integrated Travis CI in this branch. Currently build for arduino uno test only. Some other board available for test is Due, Mega, Zero and Leonardo. 

I had to make changes on sensor.cpp here (minor) just to see CI passed successfully. That's the beauty of CI, it can yield warning and error about code that want to be merged.

**Comment by hazimgharib21** [comment]
Nice one. Maybe can create new repo to store the travis build template. So that it can be use for other library as well.

**Comment by mbazli** [comment]
yes, sure can. 

if nothing else to work in here, please merge this so we can start using CI for next coding work.

**Pull request merged**
